Repository nordtheme/emacs, pull requests merged in 2020-01, with the labels that each got.

#88 Use `display-color-cells` to enable 24-bit color terminal support
  nord-theme.el
Labels: context-ui, scope-compatibility, scope-stability, type-improvement

#89 Migrate deprecated `show-paren-X-face` faces
  nord-theme.el
Labels: context-syntax, scope-compatibility, type-feature

#71 Fix cider evaluation result in terminal
  nord-theme.el
Labels: context-package-support, context-syntax, scope-compatibility, scope-ux, status-pending, type-feature

#87 Add ivy-mode support
  nord-theme.el
Labels: context-package-support, context-ui, scope-compatibility, scope-ux, status-pending, type-feature
