Repository nordtheme/emacs, pull requests merged in 2025-03, with the labels that each got.

#131 Fix `Invalid face box` error
  nord-theme.el
Labels: context-ui, priority-high, scope-compatibility, scope-stability

#135 GitHub Flow migration
  changelog.md
  readme.md
Labels: context-documentation, context-workflow, scope-maintainability, scope-compatibility, scope-stability, scope-quality

#137 From `master` to `main`
  changelog.md
  readme.md
Labels: context-documentation, context-workflow, scope-maintainability
